name: PluginGamingRoom
version: 1.0
api-version: 1.14
author: Sckoco
main: be.sckoco.plugintitle.Main
commands:
  rdm:
    description: Afficher message de redemarrage
    permission: rdm.use
  event:
    description: Afficher un message event
    permission: event.use
  rdv:
    description: Afficher message event eglise
    permission: rdv.use
  bvn:
    description: Afficher message bienvenue
  aide:
    description: Afficher une aide pour les commandes
  village:
    description: Teleporter un joueur au village
  ville:
    description: Teleporter un joueur a la ville
    permission: ville.use
  monnaie:
    description: Give la monnaie choisie
    permission: monnaie.use
  avantposte:
    description: Teleporter un joueur a l avantposte
  vague:
    description: Spawn vague de pillagers
    permission: vague.use
  soute:
    description: Teleportation pour les donateurs
    permission: donateur.use